# 设中文为默认语言，注释掉英文（保留可后续恢复）
[zh-cn]
    languageName      = "中文"
    languagedirection = "ltr"
    title             = "燕山旧时光"  # 这里改成你站点的名称，也可以保留原Example Site
    weight            = 1  # weight=1代表默认语言，Hugo优先加载

# [en]
#     languageName      = "English"
#     languagedirection = "ltr"
#     title             = "Example Site"
#     weight            = 2
