# 只保留社交菜单
[[social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/CaiJimmy/hugo-theme-stack"
  [social.params]
    icon = "brand-github"

[[social]]
  identifier = "twitter"
  name = "X"
  url = "https://twitter.com"
  [social.params]
    icon = "brand-twitter"

[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    params =
        icon = "home"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
    params =
        icon = "archive"

[[main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 3
    params =
        icon = "search"

[[main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 4
    params =
        icon = "link"
