[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

[[main]]
    identifier = "search"
    name = "搜索"
    url = "/"
    weight = 3

[[main]]
    identifier = "links"
    name = "链接"
    url = "/"
    weight = 4
