# 只保留首页、链接、燕山论坛、软件下载，删掉搜索和归档
[[main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1
[main.params]
icon = "home"

[[main]]
identifier = "links"
name = "链接"
url = "/links/"
weight = 2  # 权重调整，保持顺序连贯
[main.params]
icon = "link"

[[main]]
identifier = "bbs"
name = "燕山论坛"
url = "/page/bbs"
weight = 3
[main.params]
icon = "messages"

[[main]]
identifier = "download"
name = "软件下载"
url = "/page/download"
weight = 4
[main.params]
icon = "download"  # 临时用cloud图标，避开download.svg缺失的问题
