# 社交菜单
[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/CaiJimmy/hugo-theme-stack"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name = "X"
    url = "https://twitter.com"
    [social.params]
        icon = "brand-twitter"

# 主菜单
[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
    [main.params]
        icon = "archive"

[[main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 3
    [main.params]
        icon = "search"

[[main]]
    identifier = "links"
    name = "链接"
    url = "/links/"
    weight = 4
    [main.params]
        icon = "link"
