[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [main.params]
        icon = "logo-s"

[[main]]
    identifier = "bbs"
    name = "燕山论坛"
    url = "/page/bbs/"
    weight = 2
    [main.params]
        icon = "messages"

[[main]]
    identifier = "jiuwu"
    name = "旧物时光"
    url = "/page/jiuwu/"
    weight = 3
    [main.params]
        icon = "shopping-bag"

[[main]]
    identifier = "phonebook"
    name = "电话黄页"
    url = "/page/phonebook/"
    weight = 4
    [main.params]
        icon = "phone"

[[main]]
    identifier = "links"
    name = "友情链接"
    url = "/links/"
    weight = 5
    [main.params]
        icon = "link"

[[main]]
    identifier = "novel"  # 唯一标识符，不再重复
    name = "小说连载"
    url = "/page/novel/"       # 独立路径，和搜索区分开
    weight = 6            # 调整权重，放在友情链接后、站内搜索前
    [main.params]
        icon = "novel"     # 换个更贴合的图标（书的图标）

[[main]]
    identifier = "search"
    name = "站内搜索"
    url = "/search/"
    weight = 7
    [main.params]
        icon = "search"
