[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2
    [main.params]
        icon = "archive"

[[main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 3
    [main.params]
        icon = "search"

[[main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 4
    [main.params]
        icon = "link"
