[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "jiuwu"
    name = "旧物时光"
    url = "/page/jiuwu/"
    weight = 3
    [main.params]
        icon = "shopping-bag"

[[main]]
    identifier = "bbs"
    name = "燕山论坛"
    url = "/page/bbs/"
    weight = 2
    [main.params]
        icon = "messages"

[[main]]
    identifier = "phonebook"
    name = "电话黄页"
    url = "/page/phonebook/"
    weight = 4
    [main.params]
        icon = "phone"

[[main]]
    identifier = "links"
    name = "友情链接"
    url = "/links/"
    weight = 5
    [main.params]
        icon = "link"

# 找回搜索按钮
[[main]]
    identifier = "search"
    name = "站内搜索"
    url = "/search/"
    weight = 6
    [main.params]
        icon = "search"
