# 只保留首页、链接、燕山论坛、软件下载，删掉搜索和归档
[[main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1
[main.params]
icon = "home"

[[main]]
identifier = "links"
name = "友情链接"
url = "/links/"
weight = 2  # 权重调整，保持顺序连贯
[main.params]
icon = "link"

[[main]]
identifier = "bbs"
name = "燕山论坛"
url = "/page/bbs/"
weight = 3
[main.params]
icon = "messages"

[[main]]
identifier = "jiuwu"
name = "燕山旧物"
url = "/page/jiuwu/"   # 确保这里和你的文件夹名称一致，并带上斜杠
weight = 4             # 权重决定排序，你可以根据需要调整
icon = "download"  # 如果你的主题支持图标，可以选一个购物袋图标
